waypoints:
  restaurant:
    pose:
      x: -0.25
      y: 2.0
    orientation:
      yaw: -1.57
    track: waiting.wav
    wait_time: 5.0
  customer:
    pose:
      x: 2.0
      y: -0.5
    orientation:
      yaw: 1.57
    track: pickup.wav
    wait_time: 5.0
  parking:
    pose:
      x: -1.0
      y: -1.5
    orientation:
      yaw: -1.57
    track: parking.wav
    wait_time: 5.0